### ISSUE TITLE
Possible incorret `mbolli\` path on `pre-php-82` branch files

### ISSUE THREAD

**Issue by FontouraAbreu** [mbolli/nfsen-ng#100]
Aside from Install and Readme files, there's these `mbolli\nfsen_ng\...` paths that aren't present in the `master` branch

![image](https://github.com/mbolli/nfsen-ng/assets/68250023/f653cc12-2b2b-46b2-b399-b6f5a8a479b4)

Are these correct? If not I'm already trying to enhance the `Readme.md` and `Install.md` files so I can change it and send a PR

**Comment by mbolli** [comment]
These are correct and are part of the PSR-4 auto-loading which will be released with v0.3

**Comment by FontouraAbreu** [comment]
Alright then, I'll be closing the issue as there's no issue haha

**Comment by FontouraAbreu** [comment]
Actually, can you tell me where the log file is supposed to be?
Didn't manage to find it and were searching the code for a hint to it
