### ISSUE TITLE
nfdump folders not created when installed using NFDump

### ISSUE THREAD

**Issue by davidshirk80** [mbolli/nfsen-ng#101]
Installed exactly as specified for Ubuntu 22.04 on a VM.

None of the following directories exist that are specified in the config file:
/usr/bin/nfdump
/var/nfdump

Do we need to create the directories and give the www-data user access?

**Comment by mbolli** [comment]
The config file just contains a sane default, of course the nfdump path can be different. Use `which nfdump` to find the path to nfdump on your system and put it in the config file.

**Comment by davidshirk80** [comment]
Thank you! We can close this now!
