### ISSUE TITLE
Syntax error if nfdump equal sign no longer supported - "syntax error at 'port=80'"

### ISSUE THREAD

**Issue by falz** [mbolli/nfsen-ng#115]
Fresh install of nfsen-ng with nfdump 1.7.5. syslogs show this, repeating for any ports defined in settings.php. It then doesn't create the rrd files and spits out more errors for that

```
Exception: NfDump: Error in filter syntax. <br><b>Output:</b> Line 1: syntax error at 'port=80'
```

Looking into it further, if you issue nfdump command with "port=80" it does indeed fail. "port 80" works.

Fix is in `backend/common/Import.php`, replacing = with a space:

```
        //$nfdump->setFilter('dst port=' . $port);
        $nfdump->setFilter('dst port ' . $port);
```

I can confirm this works with older nfsen verisons as well - tested nfdump syntax on our older server which has 1.6.6.

**Comment by mbolli** [comment]
thanks for the research!
