### ISSUE TITLE
can't start ./cli.php

### ISSUE THREAD

**Issue by stefy-cooky** [mbolli/nfsen-ng#14]
i'm trying to start the deamon but i've this error :+1: 
`/var/www/html/nfsen-ng/backend/common/config.php:20
Stack trace:
#0 /var/www/html/nfsen-ng/backend/cli.php(6): common\Config::initialize()
#1 {main}
  thrown in /var/www/html/nfsen-ng/backend/common/config.php on line 20
`
I've set my settings.php like this : 
`$nfsen_config = array(
'general' => array(
        'ports' => array(
            80, 22, 53,
        ),
        'sources' => array(
            'test1',
        ),
        'db' => 'RRD',
    ),
    'nfdump' => array(
        'binary' => '/usr/local/bin/nfdump',
        'profiles-data' => '/home/netflow/test',
        'profile' => 'live',
        'max-processes' => 1, // maximum number of concurrently running nfdump processes
    ),
    'db' => array(
        'Akumuli' => array(
            'host' => 'localhost',
            'port' => 8282,
        ),
        'RRD' => array()
    ),
    'log' => array(
        'priority' => LOG_INFO, // LOG_DEBUG is very talkative!
    )
);`

I'm surely doing something wrong but i can't find out,
thanks in advance for help

**Comment by mbolli** [comment]
Was the exception thrown in backend/common/config.php on line 20? Normally that means that you didn't copy your settings.php.dist to settings.php. 
Your config looks good, except that the Akumuli config should be commented out probably.

**Comment by mbolli** [comment]
any changes after pulling the latest version?

**Comment by stefy-cooky** [comment]
I can launch the deamon :) perfect, now i need to explore data and test the API :)

**Comment by mbolli** [comment]
> Parse error: syntax error, unexpected '{', expecting identifier (T_STRING) in /var/www/html/nfsen-ng/backend/api/api.php on line 4

seems you're [not using PHP >= 7.0](http://php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing.group).

**Comment by stefy-cooky** [comment]
when i display my php version (php -v) it is => PHP 7.2.11-2

**Comment by mbolli** [comment]
that's weird, can you check that line 4 in backend/api/api.php is `use nfsen_ng\common\{Debug, Config, NfDump};` ?

**Comment by Dona21** [comment]
@stefy-cooky do you need further help ? I had an issue with cli.php lately when executing it from outside of its directory. I pushed a fix that worked for me on Ubuntu 18.04 and Centos 7. Please try to pull the last changes and let us know if you have any issue
