### ISSUE TITLE
nfcap/dump not starting

### ISSUE THREAD

**Issue by tychoo** [mbolli/nfsen-ng#15]
Installed on Ubuntu 18.04, nfsen-ng is running, no errors in the browser anymore, but I don't see any nfcapd processing running, or files created in my /var/nfdump/profiles-data/live directory.  If I manually start nfcapd it works, and I can see flow data.

Not sure what i'm missing, no errors via browser or log file pointing me to a problem.

Thanks for the help.

**Comment by mbolli** [comment]
nfsen-ng doesn't start nfcapd. But it'd be a nice feature actually...

**Comment by mbolli** [comment]
According to the [nfcapd manual](https://www.systutorials.com/docs/linux/man/1-nfcapd/) it seems to be the `-S 1` option. Didn't test it though.

**Comment by stefy-cooky** [comment]
Hello @tychoo,
If you want to create file/folder structure you can use this command :
`nfcapd -D -t 60 -p 9996 -n IDENT,IPADDRESS,/your/directory`

**Comment by tychoo** [comment]
Thanks it's creating the folder structure fine now, but I'm getting a sub dir error now, not sure what it means.

Got 503 - Service unavailable. NfDump: Internal error. Number of sub dirs must agree in '2018/10/29/nfcapd.201810290835' and '-'

**Comment by mbolli** [comment]
hmm weird. is it the same structure for all sources? in [nfdump/bin/flist.c](https://github.com/phaag/nfdump/blob/master/bin/flist.c) it checks the levels of the directories.
```c
                        // Check, how many levels of directory in path
			levels_first_file = dirlevels(path);

			if ( last_file_ptr ) {
				// path is path/to/any/first_file:last_file_ptr
				char *p, *q;
	
				// the number of sub dirs must be eqal for first_file and last_file
				if ( levels_first_file != levels_last_file ) {
					fprintf(stderr, "Number of sub dirs must agree in '%s' and '%s'\n", path, last_file_ptr);
					exit(250);
				}
```

**Comment by tychoo** [comment]
It's processing data now, maybe just needed to let nfcapd run for a while.   Thanks for the help guys.

**Comment by candlerb** [comment]
> Any idea how I can start nfcapd create the file/folder structure nfsen-ng requires?

Looking at a system with nfsen, it starts nfcapd processes like this:

```
/usr/local/bin/nfcapd -w -D -p 9995 -u netflow -g www-data -B 20000 -S 1 \
    -P /var/nfsen/var/run/p9995.pid -z -I gw -l /var/nfsen/profiles-data/live/gw
```

I don't mind if nfsen-ng doesn't start nfcapd - it just needs to be documented that this is something you should do yourself.  Why not include a example systemd unit file for it?  Here's my suggestion:

**`/etc/systemd/system/nfcapd@.service`**

```
[Unit]
Description=Netflow Capture Daemon
After=network-online.target
Wants=network-online.target
Conflicts=shutdown.target

[Service]
EnvironmentFile=-/etc/default/nfcapd
EnvironmentFile=/etc/default/nfcapd.%i
ExecStart=/usr/local/bin/nfcapd -w -p ${PORT} -u ${USER} -g ${GROUP} -B ${BUFFLEN} -S 1 -z -I %i -l /var/nfsen/profiles-data/live/%i $OPTIONS
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**`/etc/default/nfcapd`**

```
USER=netflow
GROUP=www-data
BUFFLEN=20000
#OPTIONS="-T +3,_4"
```

**`/etc/default/nfcapd.gw`**

```
PORT=9995
```

Then you do:

```
systemctl daemon-reload
systemctl start nfcapd@gw
systemctl enable nfcapd@gw
```

This lets you run multiple nfcapd instances, just like nfsen did.

**Comment by mbolli** [comment]
@candlerb 
Thanks, that is a nice suggestion.

@Dona21 
Would you be able to test this on a few systems? What's the status on the nfsen-ng daemon systemd service?

**Comment by Dona21** [comment]
@mbolli 
Yes I could test it on some ad-hoc systems but starting nfcapd is actually more related to collector itself rather than the visualizer. For example in our infrastructure we have a few lines in a shell script which systemd launches at boot.

The systemd unit for nfsen-ng is also ready but not published yet. Any recommendations about  where to put it ? New directory in backend/ like "systemd" or "services" ?
