### ISSUE TITLE
data source additional configuration

### ISSUE THREAD

**Issue by michu162** [mbolli/nfsen-ng#16]
Hello,

I'm trying to test nfsen-ng in our environment. Can you help me how too specify:
- netflow sampling rate, eg. from old nfsen: 'switch1' => { 'port' => '53962', 'col' => '#37541d', 'type' => 'netflow', 'optarg' => '-s 2048'}
- type sflow, eg. from old nfsen: 'switch2' => { 'port' => '52085', 'col' => '#60400d', 'type' => 'sflow'}

Regards,
Michal

**Comment by mbolli** [comment]
Hi Michal

nfsen-ng currently doesn't start nfcapd. You have to start nfcapd by yourself (PRs welcome).
So this config should be enough:
```php
<?php
$nfsen_config = array(
    'general' => array(
        'ports' => array(
            80, 22, 53, 23 // or other ports
        ),
        'sources' => array(
            'switch1', 'switch2'
        ),
        'db' => 'RRD',
    ),
  ...
);
```

**Comment by Dona21** [comment]
you can have a look at how nfcapd has been invoked by the "old nfsen" in your working environment:

```bash
ps -aux | grep nfcapd
```

then use the command(s) you get from the output to either start them manually or pack them in a systemd service unit to start automatically at boot
