### ISSUE TITLE
getting a graph based on a filter 

### ISSUE THREAD

**Issue by hans-mayer** [mbolli/nfsen-ng#19]
Dear All, 

In the "Flows" tab we are able to define some advanced filters. Is there a way to see these results in the same way as graph over time as it is possible in the "Graphs" tab ? 
Or to take over the filter definition into the graphs result ? 
I couldn't find anything. 

Output type "Custom" could be a solution. But no idea what the "custom output format" should be. 

Kind regards 
Hans 

--

**Comment by mbolli** [comment]
Hi Hans

I somehow missed this, but better late than never:

- The graphs are being generated from data stored in the RRD database. We can't use nfdump filters on this data.
- In the latest master version, there is a help text for the Custom Output Format. It accepts the same parameters as nfdump, e.g. %ts %dp %da etc.

Regards
Michael
