### ISSUE TITLE
Bit/s instead of Bytes

### ISSUE THREAD

**Issue by righter83** [mbolli/nfsen-ng#21]
Hi

you are showing the traffic in Bytes per second.
is there any possiblity to change it to Bits per second?

**Comment by lbsou** [comment]
My first command on your project. I am very impressed by the work you did (your team). I think this is a very nice piece of software. 

I do agree with @righter83 that bits instead of bytes would be more "network people readable".

Thank you!

**Comment by studypyth** [comment]
Hello, do you have news about this issue?

**Comment by mfrisoni** [comment]
Hi
I think it's important to have bit/s as measure unit for traffic.
Can you give a feedback pls ?
Thank you.

**Comment by mikejwolfmann** [comment]
Has anyone patched this?

**Comment by subsecond** [comment]
Tested in the `prep-php-82` branch: The new "traffic unit" switcher (with the new default set to bits/s) is a really nice addition, thank you!
