### ISSUE TITLE
how to config httpd.conf

### ISSUE THREAD

**Issue by gothack329** [mbolli/nfsen-ng#22]
`index.html` is under `/frontend/`, so I open the webpage  with 'http://localhost/nf-sen-ng/frontend/index.htm'

then i got an error:"The requested URL /nfsen-ng/api/config was not found on this server."

how to solve this problem...

**Comment by mbolli** [comment]
did you enable the apache modules listed in the installation manual?
```bash
# enable apache modules
a2enmod rewrite deflate headers expires
```
pointing the browser to /nfsen-ng should be enough.

**Comment by gothack329** [comment]
> did you enable the apache modules listed in the installation manual?
> 
> ```shell
> # enable apache modules
> a2enmod rewrite deflate headers expires
> ```
> 
> pointing the browser to /nfsen-ng should be enough.

it seems that there is no this command in centos，i will try it manually, thx

**Comment by Dona21** [comment]
installation notes for Centos 7 are now available.
Hope this helps

**Comment by DocMAX** [comment]
I have the same problem.
installed rewrite deflate headers expires.
/nfsen-ng just shows me the file content.

**Comment by Dona21** [comment]
Hi @DocMAX ,

Did you encounter any error/problem during nfsen-ng installation or any of the related dependencies ?

Please answer a few questions questions and I will try to help.

1) On which operating system are you running nfsen-ng ?
2) Did you encounter any error/problem while installing nfsen-ng and its dependencies from the installation notes ?
3) Copy and paste the output of this command : `sudo apachectl -M`
4) `cd` in the nfsen-ng directory and copy and paste the output of this command (you might need to install "`tree`") : `sudo tree -aghu`
5) which version of php is installed : `php -v `

**Comment by DocMAX** [comment]
I had to add this:

    <Directory /var/www/html/>
        AllowOverride All
    </Directory>
