### ISSUE TITLE
timezone problem

### ISSUE THREAD

**Issue by gothack329** [mbolli/nfsen-ng#23]
i want to know how to set timezone, the graph time is later than local time...my timezone is utc+08:00

![image](https://user-images.githubusercontent.com/1442226/54013063-eac0d180-41b2-11e9-9453-c7dcd371cd8a.png)

**Comment by mbolli** [comment]
nfsen-ng uses `date_default_timezone_get()`, which in turn queries the php.ini `date.timezone` attribute. Can you set this and retry?

**Comment by gothack329** [comment]
> nfsen-ng uses `date_default_timezone_get()`, which in turn queries the php.ini `date.timezone` attribute. Can you set this and retry?

it works, thx
