### ISSUE TITLE
Report on all ports

### ISSUE THREAD

**Issue by RhinoLance** [mbolli/nfsen-ng#24]
Hi,

Is it possible to review traffic on all ports, without having to specify each one?

Every evening/night my internet usage spikes for a couple of hours, burning up to 20 GB of data (I would generally see 2 GB for the rest of the day).  I have been had nfcapd running for the past several days.

At the moment my nfsen-ng configuration file has ports 80 and 443 specified, but can't see the usage spikes in the data, so assume it may be on another port, but don't know which ports to even try.

Any thoughts would be appreciated.

**Comment by mbolli** [comment]
Not without specifying each one. And it might take a bit more resources on the nfcapd side as well. Would be interesting to see how much exactly, though... Does the spike show up in the protocols view?

**Comment by Dona21** [comment]
Hi,

In your case I would probably try to identify the port(s) with nfdump first. How many sources do you have ?

Assuming you have only one source and that the source is "source1", you could give a try with the below command (date in this case is May 8th).
The path might be different depending on where your data is stored.

`nfdump -R /var/nfdump/profiles-data/live/source1/2019/05/08 -s port:p -O bytes`

You may also dump the whole thing with the below command and further process it somehow:
`nfdump -R /var/nfdump/profiles-data/live/source1/2019/05/08`

Hope this helps

**Comment by RhinoLance** [comment]
Thanks Dona.  Your answer about processing the data and analysing in another program will probably make it easier.  A follow up question though, when I process with nfdump -r, say 
`2019/05/06/nfcapd.201905062100`
I would expect that to show the processed data for 6th May, somewhere around 9pm.  Yet the tail of the output shows:
`Time window: 2019-05-07 05:30:08 - 2019-05-07 06:04:34`
Why the discrepency in time?  My system has the timezone set as GMT +10, so that's not consistent with the offset.  I've confirmed that my netflow src is also set to the same timezone.

Thoughts?

**Comment by Dona21** [comment]
I tried to run something like your command and check how it behaves on my system.
I do get a more or less correct value for the second part of the "Time window", though the first part of it seems to exceed the 5 minutes slots.

The header looks something like this :
`"Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows"`

I assume that "Date first seen" is related to when the flow started (has been seen and generated for the first time) at the netflow exporter (the source). Not a netflow guru but I assume the exporter sends it only when the flow is "kind of completed".

This however does not answer your question and maybe it could be a good idea to ask for help on the nfdump github page (https://github.com/phaag/nfdump) in which people are used to that tool and maybe encountered this issue already.

I do start the collector (nfcapd) manually in my environment (not using nfsen) but not sure if this is related or not. How do you start your collector ?

The only thing I've done on that system regarding the time (not related to nfdump) is
`timedatectl set-timezone Europe/Zurich`

A possibility could be to use wireshark on the collector and try to get the netflow packets and see if the date there is OK there or not. No idea on how nfcapd handles that.

This is at least what I would try to do, hope that somehow helps
