### ISSUE TITLE
why not

### ISSUE THREAD

**Issue by BEncounter** [mbolli/nfsen-ng#29]
Got 503 - Service unavailable. NfDump: Internal error. stat() error '/var/nfdump/profiles_data/live/source1/2019/07/31/nfcapd.201907310405': Permission denied

**Comment by Dona21** [comment]
Hi,

Probably some issues with files or folders permissions. Try to execute this command and post back the result : 

`ls -la /var/nfdump/profiles_data/live/source1/2019/07/31/`

**Comment by fernandezteran** [comment]
Hi, sorry for revive this issue but i have the same problem and don't find any sollution.

I'm pretty sure that i have the right permissions in my nfcapd files. Any idea?

Kind reggards.

**Comment by Dona21** [comment]
Hi @fernandezteran ,

Which operating system?

Please share the output of the command you are running and the subsequent error message(s).

Any useful syslog messages related to this matter could also help.

Kind regards
