### ISSUE TITLE
Error creating rrd file: not writable

### ISSUE THREAD

**Issue by benweltevrede** [mbolli/nfsen-ng#30]
Hello,
I am trying to get nfsen-ng to work on Ubuntu 18.04 system. I followed the instructions but when I am trying to import nfdump files I get the message (in /var/log/syslog) 
**nfsen-ng: Error creating /var/www/html/nfsen-ng/backend/datasources/data/1234.rrd: Not writable**
All the directories from /var/www down are owned by www-data and have rw privileges for www-data. 
What am I doing wrong?

**Comment by Dona21** [comment]
Hi,
Did you try to run import with a "normal" user ?
Try the import command again with sudo or with root user directly and let me know

**Comment by Dona21** [comment]
Just checked our test system and files are owned by root too, so it should not be a problem.
the user www-data needs a read permission on files (to display it in the nfsen-ng frontend) which it seems to have in your case.
do you see the erorr message in the logs or in the nfsen-ng frontend ?
does your "/var/www/html/nfsen-ng/backend/datasources/data/" directory have the execute pemission for "other" users ?

**Comment by benweltevrede** [comment]
Thanks for your fast replies!
I see the error messages in /var/log/syslog.
Yes. The /var/www/html/nfsen-ng/backend/datasources/data/" directory has execute privileges for everyone. (The directories above it have them as well,)

![files](https://user-images.githubusercontent.com/52342606/64850128-19fa4480-d615-11e9-9510-7fce8ad1e8e1.png)

**Comment by Dona21** [comment]
you are welcome, my pleasure to help (if I can).
did you get this error while trying to start the daemon ?
if yes, did you use a normal user ?

**Comment by benweltevrede** [comment]
Actually I did not start a daemon - just wanted to load existing files (there is no nfcapd daemon running on this machine)
But I started the daemon - no error messages: nfsen-ng: CLI: Starting daemon...

**Comment by benweltevrede** [comment]
Succes! Not sure what I did, but I do get data on the graphs.

**Comment by Dona21** [comment]
in an attempt to furether help you, I:
- deployed a new VM and installed Ubuntu 18.04 server (from scratch) with the latest ISO available
- proceeded to follow instructions regarding nfsen-ng installation (everything done with root user)
- created a path to hold some nfcap files (still root) : `mkdir -p /var/nfdump/profiles-data/live/source1/2019/09/13/`
-> at this point permissions are set as `drwxr-xr-x` and ownership is `root `for the whole directory tree
- copied a subset of nfcap data from our production server to this new VM
-> files ownsership:` -rw-rw-r-- 1 root root  14K Sep 13 01:50 nfcapd.201909130345`
- modified `/var/www/html/nfsen-ng/backend/settings.php` to hold only `source1` (the rest is unchanged)
- `cd /var/www/html/nfsen-ng/backend && sudo ./cli.php -f -p -ps import`

it worked on my side so no clue

**Comment by benweltevrede** [comment]
Thanks for your help! Much appreciated.
Ben
