### ISSUE TITLE
Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by zavndw** [mbolli/nfsen-ng#43]
Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 60

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 60

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 60

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 64

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 60

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 64

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 60

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 64

Deprecated: Function ReflectionType::__toString() is deprecated in /srv/http/nfsen-ng/backend/api/api.php on line 60

PHP 7.4.3

**Comment by namlicniku** [comment]
Deprecated: Function ReflectionType::__toString() is deprecated in /var/www/html/nfsen-ng/backend/api/api.php on line 60...

Same for me. Ubuntu 20 / PHP 7.4.3

**Comment by mbolli** [comment]
Thanks @zavndw and @namlicniku for the report!
