### ISSUE TITLE
./cli.php status  Not running

### ISSUE THREAD

**Issue by studypyth** [mbolli/nfsen-ng#45]
Hello, i install soft by readme but after configuration i try to start nfsen, but i got error (see bellow)

ipcore@nfseng-ng:/var/www/html/nfsen-ng/backend$ ./cli.php start -v
2020-04-16 06:49:57 CLI: Starting daemon...
int(0)
Daemon running, pid=30296
ipcore@nfseng-ng:/var/www/html/nfsen-ng/backend$ ./cli.php status 
Not running

**Comment by mbolli** [comment]
Is there anything in syslog?

**Comment by studypyth** [comment]
How can i see log messages? 
--
Отправлено из Mail.ru для Android четверг, 16 апреля 2020, 02:03PM +06:00 от Michael Bolli  notifications@github.com :

**Comment by mbolli** [comment]
depends on your system. try `tail -f /var/log/syslog` or `tail -f /var/log/messages`

**Comment by studypyth** [comment]
Apr 16 10:16:05 nfseng-ng nfcapd[17420]: Ident: 'none' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
Apr 16 10:16:05 nfseng-ng nfcapd[17420]: Total ignored packets: 0
Apr 16 10:17:01 nfseng-ng CRON[54264]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Apr 16 10:21:05 nfseng-ng nfcapd[17420]: Ident: 'none' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
Apr 16 10:21:05 nfseng-ng nfcapd[17420]: Total ignored packets: 0
Apr 16 10:23:01 nfseng-ng CRON[54946]: (root) CMD (   test -x /etc/cron.daily/popularity-contest && /etc/cron.daily/popularity-contest --crond)
Apr 16 10:25:50 nfseng-ng php: nfsen-ng: CLI: Starting daemon...
Apr 16 10:26:05 nfseng-ng nfcapd[17420]: Ident: 'none' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
Apr 16 10:26:05 nfseng-ng nfcapd[17420]: Total ignored packets: 0

**Comment by studypyth** [comment]
i solved problem, thank you for your help
