### ISSUE TITLE
Expire and Max Size

### ISSUE THREAD

**Issue by studypyth** [mbolli/nfsen-ng#46]
Hello,
Can i configure analog of parameter 'Expire' and 'Max size', its mean how long we can store data before auto deleting?

**Comment by Dona21** [comment]
Hi, the data that are written in the TSDB (the rrd files) is fix size already and it rotates. For anything related to the nfcapd (flow capture files) you should check on the nfdump page if that exists. As an alternative you could use the `cron` utility and write a cron job
