### ISSUE TITLE
Port information missing under flows and statistics

### ISSUE THREAD

**Issue by tb2496** [mbolli/nfsen-ng#48]
Hi, src and dst ports do not show regardless of the output type selected from dropdown:

![ports](https://user-images.githubusercontent.com/63508056/81406482-af4bcb00-9107-11ea-8395-07e2a4cb8eb3.jpg)

**Comment by art0** [comment]
I have the same issue, i can not display the flows by port

**Comment by mbolli** [comment]
thanks both @tb2496 and @art0 for noticing this, should be fixed in master.
