### ISSUE TITLE
sp and dp not displayed

### ISSUE THREAD

**Issue by art0** [mbolli/nfsen-ng#49]
How to reproduce

- Nfdump returns a full CSV with the source and destination  port of the flows
- I select any format that contains %dp 
Ports are not displayed in the GUI

Get CSV: returns the CSV with those fields

**Comment by mbolli** [comment]
Duplicate of #48

**Comment by art0** [comment]
What is the syntax for the Custom $format in the GUI?
Thanks for quick response

**Comment by mbolli** [comment]
@art0 this didn't work until now. I just fixed it. You can use the nfdump formats as specified in the docs, e.g. https://manpages.ubuntu.com/manpages/xenial/man1/nfdump.1.html#output%20formats
