### ISSUE TITLE
Selecting a single 5-minute bucket - 503 error

### ISSUE THREAD

**Issue by candlerb** [mbolli/nfsen-ng#53]
(Expansion of issue mentioned in #31)

One of the things I do most often in nfsen is to move the marker to a single 5-minute bucket. For example, see the peak at 20:55 (UTC) here:

![image](https://user-images.githubusercontent.com/44789/84478622-8c25b580-ac89-11ea-81ca-9edbd5031b16.png)

It's very easy then to run queries on this bucket in the bottom half.

Using nfsen-ng, the same peak exists (note: this time it's showing local time, BST, so it's at 21:55)

![image](https://user-images.githubusercontent.com/44789/84478732-b1b2bf00-ac89-11ea-85a7-02d0895a8452.png)

So I then drag the start and end boundaries as close as I can around the peak:

![image](https://user-images.githubusercontent.com/44789/84479050-30a7f780-ac8a-11ea-86d6-398a7066c8a8.png)

and switch to "Statistics" - but unfortunately I get a 503 error when running the query.

![image](https://user-images.githubusercontent.com/44789/84479121-4fa68980-ac8a-11ea-806b-8c40efd70174.png)

It *does* work if I select a larger time range, say 15 minutes, but that dilutes the query somewhat.

So I see two issues here:

* work out why the 503 error is occuring, and prevent it (it's reproducible)
* provide in the UI a convenient way to select a single 5-minute bucket.  For example, hovering over the graph shows a big dot on the point, but clicking on it currently doesn't do anything - so a click to select the time range that the point covers would be great.

**Comment by candlerb** [comment]
I'm not sure if this bug is related to the change, but I just tried this.  Click to zoom is accepted, but when I go to Statistics and try to show top bytes for "Any IP Address", I get:

```
General error:
Notice: Undefined index: ipv6 in /var/www/html/nfsen-ng/backend/api/api.php on line 183
["\/usr\/local\/bin\/nfdump -M '\/var\/nfsen\/profiles-data\/live\/gw1:gw2' -R '2020\/09\/11\/nfcapd.202009111800:2020\/09\/11\/nfcapd.202009111800' -n '10' -o 'csv' -s 'ip\/bytes' 2>&1
<\/b>",["ts","te","td","pr","val","fl","flP","pkt","pktP","byt","bytP","pps","bps","bpp"],["2020-09-11 17:59:02","2020-09-11 18:04:31","328.670","any","XXXX::45","199","19.1","6691","54.1","542335","23.7","20","13200","81"],... snip rest of flow records...]
```

**Comment by mbolli** [comment]
not related, but fixed!

**Comment by candlerb** [comment]
Great, thank you!

FYI: the "Full IPv6 address" button does add or remove the `-6` option to nfdump, but AFAICS, it makes no difference to the output.  I see the full IPv6 address both times.

nfsen-ng sets `-o csv`, and testing shows that nfdump gives the full IPv6 address always with `-o csv`. (I am using nfdump version 1.6.20).  The `-6` flag does affect the output when no `-o` is provided, or `-o line`.

**Comment by mbolli** [comment]
Thanks for the investigation -- on my testing setup I have no ipv6 at all, so I assumed some people still might use it.
The output field selectors like `line` is processed/filtered by nfsen-ng itself, as csv output is always full. I'll probably drop the ipv6 flag entirely then.
