### ISSUE TITLE
Preferred views

### ISSUE THREAD

**Issue by candlerb** [mbolli/nfsen-ng#54]
To make life simpler in normal operation, I would prefer:

* the default graph view to be "Traffic" rather than "Flows"
* the default statistics "order by" to be "Bytes" rather than "Flows"
* traffic to be shown as bits/sec rather than bytes/sec

I realise that not everyone shares my preferences, but perhaps these could become options in `settings.php`?

**Comment by mbolli** [comment]
The first two are now possible. Have a look at the `settings.php.dist` file on master.

The third one won't be easily done, as the whole RRD import process would need to be changed. But I noticed you're not the only one asking for this.
