### ISSUE TITLE
503 error on subnet aggregation with missing prefix length

### ISSUE THREAD

**Issue by candlerb** [mbolli/nfsen-ng#55]
(Expansion of issue from #31) This is a minor usability / data validation issue.  To reproduce:

* Go to Graphs tab, select last 24 hours
* Go to Flows tab
* Under `IP Aggregation > Source` select "IPv4 subnets", but leave the prefix length empty 
* Click Process Data

Result is a red 503 error:

![image](https://user-images.githubusercontent.com/44789/84480954-44a12880-ac8d-11ea-8989-095b1e0e16be.png)

```
Got 503 - Service unavailable. NfDump: Initialization failed. /usr/local/bin/nfdump -M '/var/nfsen/profiles-data/live/gw' -R '2020/06/11/nfcapd.202006110810:2020/06/12/nfcapd.202006120805' -c '20' -o 'csv' -a '-Asrcip4' 2>&1
```

The problem is fixed if you type (say) "24" in the prefix length box.

I think the issues are:

- if nfsen-ng shows grey "/24" in the box, the user assumes that /24 is already taken as default
- if you type "/24" it fails since this is only a 2-digit box; then you realise you have to enter "24"

I think it would be better if the slash were moved out of the selection boxes:

```
      [ IPv4 Subnets     ] / [   ]
```

The box can display a grey "24" (making it clearer what the user is expected to enter here).  Then if the user leaves this blank, 24 can be supplied to the backend.

**Comment by mbolli** [comment]
Fixed in 5f2702e6e6d38dfa66e05a502b121752525bf5a0. When I find a way to add the slash as a "watermark" in the input field, I will do so.

**Comment by candlerb** [comment]
How about you just put a literal slash character in front of the input box?

**Comment by mbolli** [comment]
This messes with the grid system and puts the subnet input box on the next line.

**Comment by candlerb** [comment]
WFM if I reduce `width: 30%` to `width: 25%` on the prefix box, and insert

```
<div class="pull-left" style="width: 5%; font-size: 170%; text-align: center;">/</div>
```
before it.

![image](https://user-images.githubusercontent.com/44789/94798902-31e86600-03da-11eb-8f32-cd594aecfa6f.png)

**Comment by mbolli** [comment]
managed to do it in the input field :) thanks anyway.
