### ISSUE TITLE
NFDUMP filter "-o nel" does not work

### ISSUE THREAD

**Issue by glueck05** [mbolli/nfsen-ng#57]
Hello, i try to use the nfdump filter "-o nel" to see Nat Events with nfsen-ng. If i try to use the NFDUMP-Filter text field under Flows the filter is added wrong to the nfdump command.

Output:
/usr/local/src/nfdump-1.6.20/bin/nfdump -M '/var/flows/rt1.mn.coe' -R '2020/06/17/nfcapd.202006170845:2020/06/18/nfcapd.202006182240' -c '20' -o 'csv' -a '-Asrcip' **'-o nel'**

Correct would be:
/usr/local/src/nfdump-1.6.20/bin/nfdump -M '/var/flows/rt1.mn.coe' -R '2020/06/17/nfcapd.202006170845:2020/06/18/nfcapd.202006182240' -c '20' -o 'csv' -a '-Asrcip' **-o 'nel'**

I am not sure if this is really an issue or an enhancement request.

thanks,
glueck

**Comment by mbolli** [comment]
Hi, thanks for the feedback.

> Correct would be:
> /usr/local/src/nfdump-1.6.20/bin/nfdump -M '/var/flows/rt1.mn.coe' -R '2020/06/17/nfcapd.202006170845:2020/06/18/nfcapd.202006182240' -c '20' -o 'csv' -a '-Asrcip' **-o 'nel'**

It's working as expected. The nfdump filter is e.g. `dst port 80`, specifying new options doesn't work there.
It looks like `nel` is another output format. Do you know if there's a possibility to dump nel data in csv?
