### ISSUE TITLE
No data in Web UI, but rrd files are generated

### ISSUE THREAD

**Issue by sveneb** [mbolli/nfsen-ng#61]
Hi
I manage to get nf dump files generated, and also the rrd files are being generated and updated. 
Currently I have both the basement_[port].rdd files and the [port].rdd files being updated.
I am running the newest version from 17 of July this year

Is there a way to check if the rrd files contain any data?

What could be the reason why I am not seeing anything on the web UI.
When I try the default values for 24H under the statistics it show the following on the web ui:
![image](https://user-images.githubusercontent.com/15855821/93578683-e9728680-f99d-11ea-9da2-c13bfdb6451e.png)

Settings file
```
<?php
/**
 * config file for nfsen-ng
 *
 * remarks:
 * * database name = datasource class name (case-sensitive)
 * * log priority should be one of the predefined core constants prefixed with LOG_
 */

$nfsen_config = array(
    'general' => array(
        'ports' => array(
           80,443 ,
        ),
        'sources' => array(
            'basement',
        ),
        'db' => 'RRD',
        'processor' => 'NfDump',
    ),
    'frontend' => array(
        'reload_interval' => 60,
    ),
    'nfdump' => array(
        'binary' => '/usr/local/bin/nfdump',
        'profiles-data' => '/var/nfdump/profiles-data',
        'profile' => 'live',
        'max-processes' => 1, // maximum number of concurrently running nfdump processes
    ),
    'db' => array(
      //  'Akumuli' => array(
            //'host' => 'localhost',
            //'port' => 8282,
       // ),
        'RRD' => array()
    ),
    'log' => array(
        'priority' => LOG_DEBUG, // LOG_DEBUG is very talkative!
    )
);
```

**Comment by sveneb** [comment]
Found that the php part was not installed correctly

**Comment by moozer** [comment]
@sveneb I might be experiencing a similar issue. 

What was it that was not "installed correctly"?
