### ISSUE TITLE
Solved: rrd_xport failed. Cannot parse vname

### ISSUE THREAD

**Issue by WimRoose** [mbolli/nfsen-ng#63]
Stumbled upon this after a fresh install on RHEL7. Graph wasn't shown at all in the frontend. API Call to /api/graph response: rrd_xport failed. Cannot parse vname.

After some debugging, I found out this was not an nfsen-ng issue, but rrdgraph related: 

_`Variable names (vname) must be made up strings of the following characters A-Z, a-z, 0-9, -,_and a maximum length of 255 characters.`_

I was using a FQDN as data source name. This is not supported by RRD libs, and results in error described above.

Mentioning it here to avoid somebody else losing his time with this kind of stuff :) Maybe a warning can be added to the configuration section of the README?

Thanks @mbolli for your great work!

**Comment by mbolli** [comment]
Thanks for reporting this!
