### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by blackyzero** [mbolli/nfsen-ng#65]
Hello,

I tried to start the nfsen-ng, but there is no process after running this command:
`# ./cli.php -v start
2020-12-23 14:04:44 CLI: Starting daemon...
int(0)
Daemon running, pid=27805`

There is no log in syslog, kern or message.

Please advice how to fix the issue.
Thanks a lot.

**Comment by Dona21** [comment]
Hello @blackyzero 

Did you import the data before using the daemon ?

Example with : `./cli.php -f -p -ps import`

During the import you might get some hint if something goes wrong.

Referencing #50  and #30 

Kind regards

**Comment by blackyzero** [comment]
Hi @Dona21 ,

No i didn't import. It's a fresh install of nfsen-ng.
Do i need to collect some data first before executing the command?

Thank you.

**Comment by Dona21** [comment]
Yes, you need to have some data collected already (nfcapd files) and yes, you should import it before using the daemon the first time. You can read through [this](https://github.com/mbolli/nfsen-ng/issues/18#issuecomment-584742555) and this #44 at first, maybe it helps you to get started

**Comment by kimsengvit** [comment]
Hi team, i'm also very new user with nfsen and i have done installation step but i don't know how to do on configuration step so could you give me some document what to do next?

![Screenshot_4](https://user-images.githubusercontent.com/85928680/122016494-4e52f400-cdeb-11eb-8e8e-fdb98fca739a.png)
![Screenshot_1](https://user-images.githubusercontent.com/85928680/122016501-501cb780-cdeb-11eb-89d0-05cee7dff225.png)
![Screenshot_2](https://user-images.githubusercontent.com/85928680/122016504-50b54e00-cdeb-11eb-87ae-4a4d186ef77b.png)
![Screenshot_3](https://user-images.githubusercontent.com/85928680/122016506-514de480-cdeb-11eb-893e-e2b5c5c4bfab.png)

**Comment by Dona21** [comment]
Hi @NagaSambath ,

Are you a new "nfsen" user or a new "nfsen-ng" user ? These are two different things. Maybe having a look at [this](https://github.com/mbolli/nfsen-ng/issues/44#issuecomment-605875744) and [this](https://github.com/mbolli/nfsen-ng/issues/44#issuecomment-606469120) might help to start.

Do you have nfcapd data available ? If not, you should start from there (as mentioned in [the issue you are writing in ](https://github.com/mbolli/nfsen-ng/issues/65#issuecomment-750352025). If you are missing nfcapd data, check the nfdump (and related nfcapd) github page (https://github.com/phaag/nfdump) before getting started with nfsen-ng.

**Comment by NagaSambath** [comment]
Do you have configuration step like installation step? 

The installation step very good to follow. https://github.com/mbolli/nfsen-ng#installation

I just done installation step and i don't have nfcapd or .. yet. so do you have continues step after installation?

**Comment by Dona21** [comment]
The configuration step is straightforward and self explained in the settings.php file. That is all that need to me modified actually. However, "nfsen-ng" alone, does not do anything and it is useless if you have no idea how the other tool  (nfdump) works. You need to acquire data first. Not sure you read the [link ](https://github.com/mbolli/nfsen-ng/issues/44#issuecomment-605875744)I referenced. From that link :

> nfsen-ng has nothing to do with the exporter part nor the collector part. The exporter could be a network device (software or hardware) and the collector in our case is "nfcapd" from "nfdump" suite.
> 
> To sum up, "nfsen-ng" will work only if you have collected data with your collector (nfcapd) which will collect data only if you have configured an exporter correctly.

This being said, before configuring nfsen-ng you need to configure an exporter and a collector. The exporter could be hardware or software but the collector needs to be "nfcapd" from "nfdump" project. From my previous message : 

> If you are missing nfcapd data, check the nfdump (and related nfcapd) github page (https://github.com/phaag/nfdump) before getting started with nfsen-ng.

**Comment by NagaSambath** [comment]
You mean i have to configure an exporter and collector on my switch and router by set point to my nfsen-ng server?

**Comment by Dona21** [comment]
Almost. The exporter could be configured on your switch or router but the collector needs to be nfcap (which generates the nfcapd files that nfsen-ng uses). Provided that you know how to configure a flow exporter, your next step would be to install nfdump (which contains nfcapd) on a machine and a configure it somehow to capture the data sent by your flow exporter (in your case very likely a physical device). The machine used to capture the flow data can be the same as the nfsen-ng machine but it does not need to be. nfdump and nfcapd -> https://github.com/phaag/nfdump. Before to be able to have a running instance of nfsen-ng you need to have captured nfcapd files and the ability to check their content with nfdump. You therefore need an understanding of these tools before.

**Comment by perceival** [comment]
I have similar problem. Collector seams to be working, nfsen-ng process is working but still frontend is returning quite vague:
 nfdump command: <
× something went wrong. ?
Is nfsen-ng compatible with php 8.0.16?
BTW I am running it on fedora with systemd and nginx.
