### ISSUE TITLE
Can RRD Import process and daemon be run in parallel?

### ISSUE THREAD

**Issue by jongalli** [mbolli/nfsen-ng#66]
On a fresh install of nfsen-ng, where RRD files exist and need to be imported, can the cli.php daemon be started in parallel with the import?

i.e. when:

  cli.php -f -p -ps import

is running with an ETA of 24 hours (for example), can:

  cli.php start

also be running in parallel so that it continues updating in realtime any new flows saved by nfdump?

Or do we need to wait for the entire import process to finish before starting the cli.php daemon?

**Comment by Dona21** [comment]
The answer comes a bit late and you may have figured out the answer in the meantime, however here is an answer nevertheless. The daemon updates the existing time series database (in this case RRD files) and it does it by running the import command. You can't run it in parallel as this would do the same as the initial import command is already doing. However, once the first import is completed, it makes sense to start the daemon and let it complete/rotate the time series database with new data
