### ISSUE TITLE
Got 503 - Service unavailable.

### ISSUE THREAD

**Issue by plakun** [mbolli/nfsen-ng#67]
Hello, need some help with Nfsen-ng. 
Cant see any traffic data in Flow tab, when i press "Process data" got "Got 503 - Service unavailable. NfDump: Internal error. Can't stat '/data/nfdump/profiles_data/live/source1': Permission denied stat() error '2021/09/29/nfcapd.202109291530': No such file or directory".
My setting:
$nfsen_config = array(
    'general' => array(
        'ports' => array(
            9001,
        ),
        'sources' => array(
            'source1',
        ),
        'db' => 'RRD',
        'processor' => 'NfDump',
    ),
    'frontend' => array(
        'reload_interval' => 10,
        'defaults' => array(
            'view' => 'graphs', // graphs, flows, statistics
            'graphs' => array(
                'display' => 'sources', // sources, protocols, ports
                'datatype' => 'flows', // flows, packets, bytes
                'protocols' => array('any'), // any, tcp, udp, icmp, others (multiple possible if display=protocols)
            ),
            'flows' => array(
                'limit' => 50,
            ),
            'statistics' => array(
                'order_by' => 'bytes',
            ),
        ),
    ),
    'nfdump' => array(
        'binary' => '/usr/bin/nfdump',
        'profiles-data' => '/data/nfdump/profiles_data',
        'profile' => 'live',
        'max-processes' => 1, // maximum number of concurrently running nfdump processes
    ),
    'db' => array(
        'Akumuli' => array(
            //'host' => 'localhost',
            //'port' => 8282,
        ),
        'RRD' => array()
    ),
    'log' => array(
 'priority' => LOG_INFO, // LOG_DEBUG is very talkative!
    )
);
~             

files permissions:
[root@pkles backend]# ls -lah /data/nfdump/profiles_data/live/source1/2021/09/29/
total 516K
drwxrwxrwx 2 root root 4.0K Sep 29 15:40 .
drwxr-xr-x 3 root root 4.0K Sep 29 12:40 ..
-rw-r--r-- 1 root root 5.2K Sep 29 12:40 nfcapd.202109291235
-rw-r--r-- 1 root root  20K Sep 29 12:45 nfcapd.202109291240
-rw-r--r-- 1 root root  20K Sep 29 12:50 nfcapd.202109291245
-rw-r--r-- 1 root root  20K Sep 29 12:55 nfcapd.202109291250
-rw-r--r-- 1 root root  20K Sep 29 13:00 nfcapd.202109291255
-rw-r--r-- 1 root root  19K Sep 29 13:05 nfcapd.202109291300
-rw-r--r-- 1 root root  19K Sep 29 13:10 nfcapd.202109291305
-rw-r--r-- 1 root root  19K Sep 29 13:15 nfcapd.202109291310
-rw-r--r-- 1 root root  19K Sep 29 13:20 nfcapd.202109291315
-rw-r--r-- 1 root root  19K Sep 29 13:25 nfcapd.202109291320
-rw-r--r-- 1 root root  19K Sep 29 13:30 nfcapd.202109291325
-rw-r--r-- 1 root root  19K Sep 29 13:35 nfcapd.202109291330
-rw-r--r-- 1 root root  19K Sep 29 13:40 nfcapd.202109291335
-rw-r--r-- 1 root root  19K Sep 29 13:45 nfcapd.202109291340
-rw-r--r-- 1 root root  19K Sep 29 13:50 nfcapd.202109291345
-rw-r--r-- 1 root root  19K Sep 29 13:55 nfcapd.202109291350
-rw-r--r-- 1 root root  12K Sep 29 14:00 nfcapd.202109291355
-rw-r--r-- 1 root root  396 Sep 29 14:05 nfcapd.202109291400
-rw-r--r-- 1 root root  396 Sep 29 14:10 nfcapd.202109291405
-rw-r--r-- 1 root root  396 Sep 29 14:15 nfcapd.202109291410
-rw-r--r-- 1 root root  396 Sep 29 14:20 nfcapd.202109291415
-rw-r--r-- 1 root root  396 Sep 29 14:25 nfcapd.202109291420
-rw-r--r-- 1 root root  396 Sep 29 14:30 nfcapd.202109291425
-rw-r--r-- 1 root root  396 Sep 29 14:35 nfcapd.202109291430
-rw-r--r-- 1 root root  396 Sep 29 14:40 nfcapd.202109291435
-rw-r--r-- 1 root root  396 Sep 29 14:45 nfcapd.202109291440
-rw-r--r-- 1 root root  396 Sep 29 14:50 nfcapd.202109291445
-rw-r--r-- 1 root root  396 Sep 29 14:55 nfcapd.202109291450
-rw-r--r-- 1 root root  396 Sep 29 15:00 nfcapd.202109291455
-rw-r--r-- 1 root root  396 Sep 29 15:05 nfcapd.202109291500
-rw-r--r-- 1 root root  16K Sep 29 15:10 nfcapd.202109291505
-rw-r--r-- 1 root root  20K Sep 29 15:15 nfcapd.202109291510
-rw-r--r-- 1 root root  20K Sep 29 15:20 nfcapd.202109291515
-rw-r--r-- 1 root root  20K Sep 29 15:25 nfcapd.202109291520
-rw-r--r-- 1 root root  20K Sep 29 15:30 nfcapd.202109291525
-rw-r--r-- 1 root root  19K Sep 29 15:35 nfcapd.202109291530
-rw-r--r-- 1 root root  20K Sep 29 15:40 nfcapd.202109291535

**Comment by Dona21** [comment]
Hello, based on what you provided, I assume you could successfully import some data for the graph with the root user, correct ?

If so, your config (which I did not read) should be fine and you only need to find the permissions problem related to the webserver user who runs the commands requested by the web frontend.

If not, try to import the data so that you can discard a "settings.php" config problem.

**Comment by Dona21** [comment]
You are welcome, however the answers to my questions above would be more helpful to further help you rather than additional questions, lol. This being said, yes, it is apache that executes the command that finally retrieves the data. The correct permissions are needed along the whole path (all directories) to the file.

**Comment by plakun** [comment]
Yes, import of data was succesfull. I change permissions on nfdump data folder but still have this problem.

[root@pkles-gt0002441 backend]# chown -R apache:apache /data/
[root@pkles-gt0002441 backend]# ./cli.php -f -p -ps import
2021-09-30 06:12:42 CLI: Starting import
Resetting existing data...

Processing 1 sources...                         0.0% 0/1097 ETC: ???. Elapsed: < 1 sec [>                              ]Processing source source1 (1/1)...
Scanning /data/nfdump/profiles_data/...100.0% 1097/1097 ETC: < 1 sec. Elapsed: 5 secs [===============================]]

[root@pkles-gt0002441 backend]# ./cli.php start
2021-09-30 06:13:00 CLI: Starting daemon...
int(0)
Daemon running, pid=31751
[root@pkles-gt0002441 backend]# ./cli.php status
Running: 31751
[root@pkles-gt0002441 backend]# systemctl restart httpd

![image](https://user-images.githubusercontent.com/25481326/135380766-3ef92541-df15-44cc-a57f-8aa46b044e8e.png)

**Comment by plakun** [comment]
Problen is solved. There was no +x flag on /profiles_data. 
"chmod +x -R /data" helped. Thanks for help!
