### ISSUE TITLE
Using composer for dependencies

### ISSUE THREAD

**Issue by mbolli** [mbolli/nfsen-ng#75]
Thinking about adding some dev tools to ensure code quality, and maybe add some tests. 
This would also enable the project to fetch the only 3rd party dependency there is (the CLI progress bar) via composer. Although I might have to produce my own fork of the project, as there have been [some fixes](https://github.com/mbolli/nfsen-ng/commits/master/backend/vendor/progressbar.php) which are not in the [original repo](https://github.com/AD7six/php-cli-progress-bar).

Any thoughts for/against this?

**Comment by mbolli** [comment]
That's true and why I'm opening this issue as well. In this case though, the original repo hasn't received any changes since 9 years. So it just is not according to best practices, but security-wise does not matter.

**Comment by xtaran** [comment]
Ok, yeah, 9 years is a long time indeed.

**Comment by mbolli** [comment]
Composer autoloading is introduced in #90
