### ISSUE TITLE
Please don't use "B" as unit prefix for "Billion" but use "G" for "Giga"

### ISSUE THREAD

**Issue by xtaran** [mbolli/nfsen-ng#76]
nfsen-ng seems to use a mix of standard and non-standard unit prefixes:

* K for kilo (should be lower case though to be a proper prefix)
* M for Mega or Million (ok)
* B for probably Billion (but should be "G" for "Giga")

Later ones should be (but are probably not):

* T for Tera
* P for Peta
* E for Exa

etc. See https://en.wikipedia.org/wiki/Unit_prefix

**Comment by mbolli** [comment]
There is an option in the graphing library to try out:

Is it better after replacing `labelsKMB` with `labelsKMG2`?
https://github.com/mbolli/nfsen-ng/blob/b425d55cabe1e21803353db4d5b0299e376c2de6/frontend/js/nfsen-ng.js#L696

**Comment by mbolli** [comment]
fixed in 3628bd3580b09bc7c6c1f017e5f2296e913b8d5d (not yet in master)
