### ISSUE TITLE
Disk Limit / Low-Water

### ISSUE THREAD

**Issue by platinum55** [mbolli/nfsen-ng#78]
Hello,

in the original nfsen there is a config option called "low_water", so when the disk usage reaches the limit, old samples are getting deleted. Is there anything similar in nfsen-ng? Couldn't find such option

**Comment by Dona21** [comment]
Hi, no, it is only a visualizer built on top of nfdump tools, it does only read existing data (nfcapd files) but is not responsible of the data management in any way (collection, storage, deletion,...). Maybe there is such a feature in the nfdump tools directly, try checking in that direction [https://github.com/phaag/nfdump/search?q=low_water](https://github.com/phaag/nfdump/search?q=low_water)

**Comment by platinum55** [comment]
Oh yes! thank you very much for that quick response and hint :)
