### ISSUE TITLE
i need instruction on how to set it to start collecting like the old nfsen

### ISSUE THREAD

**Issue by wakozuka** [mbolli/nfsen-ng#79]
![image](https://user-images.githubusercontent.com/28747650/170494337-4dd91f5f-59d1-4acc-9863-a6c82ea9b509.png)
am stuck as the picture shows

**Comment by Dona21** [comment]
Hi @wakozuka , similar as #65 in particular this [65#issuecomment-861326821](https://github.com/mbolli/nfsen-ng/issues/65#issuecomment-861326821)
