### ISSUE TITLE
Support for profiles with 30s cycletime

### ISSUE THREAD

**Issue by andersonreloaded** [mbolli/nfsen-ng#80]
Hi All,

Thanks to @mbolli and team for the beautiful nfsen-ng!
After using for a week, attempted to created profiles with 30s cycle time instead of the default 5 minute cycle.
The nfcapd files were generated in the format `nfcapd.YYYYMMDDHHMM` are now being generated in `nfcapd.YYYYMMDDHHMMSS.`
Since then the graphs are not getting updated in nfsen-ng.
Is there any configuration related to the profile cycle time and format?

Best wishes

**Comment by Dona21** [comment]
Hi @andersonreloaded ,

At this time, only the 5 minutes cycle is supported as per the description [here](https://github.com/mbolli/nfsen-ng#configuration:~:text=next%20step%3A%20configuration-,Configuration,var/nfdump/profiles_data/live/source1/2018/12/01/nfcapd.201812010225.,-The%20default%20settings)
