### ISSUE TITLE
No limit on number of flows to export

### ISSUE THREAD

**Issue by neotheonce** [mbolli/nfsen-ng#81]
Hello,

Is it possible to set no limit on number of flows while exporting flows to CSV file? currently there is hard limit set from one of the value 20,50,100,500,1000.10000. How can we download CSV files without any limit

**Comment by Dona21** [comment]
Hi @neotheonce , currently, this is not supported and making an API call without the "limit" parameter will fail. Setting the value manually too high may also not be enough or result in a error while running on the backend (tried a few minutes ago). However, if you have access on the backend you can use `nfdump` to do it directly through the CLI. When you make the query to show flows for 1 hour for two sources (example: source1 and source2),  nfsen-ng shows you what command it executes on the backend, see below example :
 `/usr/local/bin/nfdump -M '/srv/nfsen/profiles-data/live/source1:source2' -R '2022/07/15/nfcapd.202207151330:2022/07/15/nfcapd.202207151415' -c '50' -o 'csv' 2>&1`

As per the nfdump man page, "-c" stands for limit. You can remove this and redirect to a file instead (example : /tmp/yourFile.csv) that would look like : 
 
`/usr/local/bin/nfdump -M '/srv/nfsen/profiles-data/live/source1:source2' -R '2022/07/15/nfcapd.202207151330:2022/07/15/nfcapd.202207151415' -o 'csv' > /tmp/yourFile.csv`

Be aware that it might take time and you may end-up with a many GB file, depending on the captured data. Usually, one would use `nfdump` directly depending on the tasks to accomplish.

Kind regards

**Comment by neotheonce** [comment]
Thank You
