### ISSUE TITLE
NfDump 1.7 compatibility

### ISSUE THREAD

**Issue by atbohmer** [mbolli/nfsen-ng#82]
Hello,
Not upgraded my nfdump 1.6.x  (from source) with nfsen-ng installation yet, but managed to do so with a nfdump 1.6.x plus nfsen setup. I needed to modify some nfsen code in order to have it work.
Question: will nfsen-ng be compatible with nfdump 1.7 or is there some work todo?
TIA!
Andre

**Comment by wherzig** [comment]
For me it looks like nfsen-ng is currently not compatible with nfdump 1.7.

I had used nfdump 1.7 on Ubuntu 20.04 and tried to get nfsen-ng to get work. Nothing was displayed. I was nearly quitting, but then I tried nfdump 1.6.28 which is part of Ubuntu 20.04. Finally nfsen-ng worked.

**Comment by atbohmer** [comment]
For me it is working from source on Redhat EL 7.9, nfdump 1.7.1 . No need to alter the nfsen-ng setup after upgrading from 1.6 to 1.7

**Comment by Tipiani** [comment]
Hello @atbohmer , please share your settings.conf file, I have the same issue as wherzig but in my case I'm using Centos 7.

and please if you can confirm if my virtualhost should to point to /var/www/html/nfsen-ng/backend or frontend, both have an index file.

Thank you!

**Comment by atbohmer** [comment]
Sorry, not using ngsen-ng anymore. The apache virtual host file containts: <Directory "/var/www/html/nfsen-ng">

**Comment by mbolli** [comment]
@Tipiani so no error message, but no data displayed?

**Comment by lukyrys** [comment]
Hi i have same problem after migration to the new server with fresh install and migration of netflow data. On old server i have nfdump 1.6.22 on new i have nfdump 1.7.1. 
Old data nfsen parse ok, new data with error bellow
@mbolli error which is 1.7 do is 
```
Mar 24 03:35:06 mail php7.1: nfsen-ng: Exception: NfDump: Internal error. Open file /home/netflow2/live/main/2024/03/24/nfcapd.202403240330: bad version: 2
```

**Comment by mbolli** [comment]
@lukyrys You need to update your files, also see https://github.com/phaag/nfdump?tab=readme-ov-file#compatibility
