### ISSUE TITLE
Add reverse DNS

### ISSUE THREAD

**Issue by wherzig** [mbolli/nfsen-ng#84]
It would be very helpful to get the hostnames displayed associated to the IP addresses using
- reverse DNS
- Using WHOIS

Using nfsen-ng is very useful to see how traffic is changed over time. On the other hand I can not identify which hosts are the source of the traffic and I do not know what are the destination networks. IP addresses are not very user friendly. Currently I use reverse DNS (i.e. the "host" command on Unix to resolve an IP address to a hostname or "whois" if there ist no hostname.

Is there any way to get the hostnames displayed of the sourced and destination IPs?

**Comment by rtrexmass** [comment]
That is a useful feature that is present in the original NFsen, it really helps, i'm currently doing it in a external script using whois, but having that on the webpage is really nice.

**Comment by subsecond** [comment]
+1 Would be really useful when under pressure.

**Comment by subsecond** [comment]
Tested in the `prep-php-82` branch: Works like a charm, thank you!
