### ISSUE TITLE
bad version: 2

### ISSUE THREAD

**Issue by wisplb** [mbolli/nfsen-ng#86]
hello how i can fix the problem 

Got 503 - Service unavailable. NfDump: Internal error. Open file /var/nfdump/profiles-data/live/source1/2022/12/16/nfcapd.202212161725: bad version: 2

**Comment by Dona21** [comment]
Hi,

This seems to come from nfdump directly and not related to nfnsen-ng -> [nffile.c](https://github.com/phaag/nfdump/blob/29477da8a673f2e444646a1c554d9819c2bbabcc/src/lib/nffile.c).

Try asking on [the nfdump github page](https://github.com/phaag/nfdump)
