### ISSUE TITLE
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated

### ISSUE THREAD

**Issue by ghost** [mbolli/nfsen-ng#88]
![image](https://user-images.githubusercontent.com/97558956/220348714-b1b5ba8d-ce3f-4621-b904-f49aa6abc6b2.png)

**Comment by mbolli** [comment]
This is a PHP 8.1 deprecation. Thanks for the report. In the meantime, PHP 7.4 is the recommended version. There should be an update sometime in the future.

**Comment by mbolli** [comment]
PHP 8.2 compatibility draft PR: https://github.com/mbolli/nfsen-ng/pull/90
