### ISSUE TITLE
extension RRD not properly integrating with PHP

### ISSUE THREAD

**Issue by huntson** [mbolli/nfsen-ng#94]
Following instructions for Ubuntu 22.04.  

After: "pecl install rrd"

I get: 
configuration option "php_ini" is not set to php.ini location
You should add "extension=rrd.so" to php.ini

I attempt" echo "extension=rrd.so" > /etc/php/8.1/mods-available/rrd.ini"

however I get 
-bash: /etc/php/8.1/mods-available/rrd.ini: Permission denied

The rrd.ini file does not exist in that directory.  Any thoughts?

**Comment by mbolli** [comment]
you probably need to perform the last command with elevated rights, e.g. sudo.
