### ISSUE TITLE
Flows are working but no graphs

### ISSUE THREAD

**Issue by r-e-m-a** [mbolli/nfsen-ng#95]
Hello,

I tried to setup nfsen-ng on Debian 12.
Flows are displayed correctly but the graphs are empty.
In den datasources i can see .rrd files named [NODE].rrd .
The gui shows no errrormessages.

Can you give me a hint what i missed?

Nodes are running  
nfpcapd -H 192.168.18.13 -i eth0 -e 60,30 -u daemon -g daemon  -D

Collector is running
/usr/bin/nfcapd -D -P /run/nfcapd.default.pid -S 1 -n node1 192.168.18.10 /data/live/node1

Tnx

**Comment by Dona21** [comment]
Hi @r-e-m-a ,

When you say the flows are displayed correctly, does this also include the date ? Currently, the nfdump version shipped with Debian 12 contains bugs that make it unusable (at least with nfsen-ng). The reason for it are the timestamps which have all the same 1970* date. If you build nfdump 1.7.3 from source, it should work.
