### ISSUE TITLE
[prep-php-82 branch] Uncaught Error: Class "nfsen_ng\common\Debug" not found 

### ISSUE THREAD

**Issue by dehnli** [mbolli/nfsen-ng#96]
On `FreeBSD 13.2-RELEASE-p4 amd64 GENERIC` using `./cli.php -f import` from `prep-php-82` branch gives:

```$ ./cli.php -f import
PHP Warning:  include_once(/usr/local/www/nfsen82/backend/common/debug.php): Failed to open stream: No such file or directory in /usr/local/www/nfsen82/backend/cli.php on line 5
PHP Warning:  include_once(): Failed opening '/usr/local/www/nfsen82/backend/common/debug.php' for inclusion (include_path='.:/usr/local/share/pear') in /usr/local/www/nfsen82/backend/cli.php on line 5
PHP Fatal error:  Uncaught Error: Class "nfsen_ng\common\Debug" not found in /usr/local/www/nfsen82/backend/cli.php:12
Stack trace:
#0 {main}
  thrown in /usr/local/www/nfsen82/backend/cli.php on line 12
```
Symlinking doesn't help as mentioned in #93 :

```
$ ln -s /usr/local/www/nfsen82/backend/common/Debug.php /usr/local/www/nfsen82/backend/common/debug.php
$ ./cli.php -v -f import
PHP Fatal error:  Cannot redeclare nfsen_ng\common\Debug::$_instance in /usr/local/www/nfsen82/backend/common/Debug.php on line 10
```
Master branch with PHP 8.2 works as expected.

@mbolli what pull do you mean to try? I could try on my testing node.

**Comment by mbolli** [comment]
@dehnli pull the latest changes on the `prep-php-82` branch, should work much better now.

**Comment by jult** [comment]
and why even use apache? nginx with php-fpm is much easier for the purpose.

**Comment by mbolli** [comment]
@jult you are welcome to submit a PR with updated installation instructions

**Comment by dehnli** [comment]
@mbolli Thanks for your efforts. Definitely works better. There is no more errors during processing source. I'll keep testing.
