### ISSUE TITLE
nginx working example solved

### ISSUE THREAD

**Issue by johndoek131** [mbolli/nfsen-ng#98]
First of all, thanks for this great software.
I referenced the [previous discussion](https://github.com/mbolli/nfsen-ng/issues/41) but it didn't work for me because the graph didn't show. The problem lies in failing to GET /api/*. It took me days to come out a working example (at least for me). Hope it helps.

    root   /var/www/;
    index  index.html index.htm index.php;

    location /nfsen-ng/ {
        alias   /var/www/nfsen-ng/frontend/;
    }
    location /api {
        rewrite ^/api/(.*)$ /nfsen-ng/backend/index.php?request=$1 redirect;
    }

**Comment by mbolli** [comment]
Thanks, pinned!
